language: java

sudo: false

jdk:
  - oraclejdk8

install: true

addons:
  apt:
    packages:
    - oracle-java8-installer

before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- java -version

env:
  global:
  - secure: f4P8Bw0z427Domw/AhnOKRFOYTXkUnPr1QO/M033FferhDivssUgcX8Rmutxy3AwKV1uYoSyJDW8Hzaj6bbJ7wbh9Yetbfo6IP8vw0gfJEvndSjpmu/x9R/0Os3jbSy4Irq5+gZZzN+ba7fySMNkBD2NoAHb/xp8RskJXPOgqas=
  - secure: Bm0zIwBo4saIBlfr9YDvNqd8UN50FeT2hZyum3RFDmJqaXiUqwxw7sCz/lRjUwTfQrvGJXQ1I8le7zE4OVQdvpn4/LwwTJIjLY2jZNjzs4mZhkHzsM5IcGcL3lukR6soVYrGloQwmw63Okw2kZxces+1fveisPIKDlVaU1RTtMQ=

after_success:
 - chmod ugo+x travis_snapshot_release.sh
 - ./travis_snapshot_release.sh
